# Generated by Django 5.2.6 on 2025-09-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'موفق'), (3, 'ناموفق')], db_index=True, default=1, verbose_name='وضعیت پرداخت')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, verbose_name='درگاه پرداخت')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='شناسه منحصر به فردی که از درگاه پرداخت دریافت می\u200cشود.', max_length=255, verbose_name='شناسه تراکنش')),
                ('gateway_response', models.JSONField(blank=True, help_text='پاسخ کامل دریافت شده از درگاه برای دیباگ و پیگیری.', null=True, verbose_name='پاسخ درگاه')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
