# Generated by Django 5.2.6 on 2025-10-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HardDeleteOrder',
            fields=[
            ],
            options={
                'verbose_name': 'deleted order',
                'verbose_name_plural': 'deleted orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='store_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stores.storeitem'),
        ),
        migrations.CreateModel(
            name='HardDeleteOrderItem',
            fields=[
            ],
            options={
                'verbose_name': 'deleted Order item',
                'verbose_name_plural': 'deleted Order items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.orderitem',),
        ),
    ]
