# Generated by Django 5.2.6 on 2025-10-10 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='نام کاربری')),
                ('status', models.CharField(default='inactive', max_length=20, verbose_name='وضعیت')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="شماره تلفن باید با فرمت '09123456789' وارد شود.", regex='^09\\d{9}$')], verbose_name='شماره تلفن')),
                ('is_seller', models.BooleanField(default=False, verbose_name='فروشنده است؟')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/', verbose_name='عکس پروفایل')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('label', models.CharField(max_length=255, verbose_name='عنوان آدرس')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='آدرس (خط اول)')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس (خط دوم)')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('state', models.CharField(max_length=100, verbose_name='استان/ایالت')),
                ('postal_code', models.CharField(max_length=20, unique=True, verbose_name='کد پستی')),
                ('country', models.CharField(max_length=100, verbose_name='کشور')),
                ('is_main', models.BooleanField(default=False, verbose_name='آدرس اصلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
            },
        ),
    ]
