# Generated by Django 5.2.6 on 2025-09-20 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="شماره تلفن باید با فرمت '09123456789' وارد شود.", regex='^09\\d{9}$')], verbose_name='شماره تلفن'),
        ),
    ]
