# Generated by Django 5.2.6 on 2025-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_is_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'آدرس', 'verbose_name_plural': 'آدرس\u200cها'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='province',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default='Tehran', max_length=255, verbose_name='آدرس (خط اول)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس (خط دوم)'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Iran', max_length=100, verbose_name='کشور'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='label',
            field=models.CharField(default='', max_length=255, verbose_name='عنوان آدرس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Tehran', max_length=100, verbose_name='استان/ایالت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='کد پستی'),
        ),
    ]
