# Generated by Django 5.2.6 on 2025-10-19 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(1, 'Progress'), (2, 'Verify'), (3, 'Done'), (4, 'Failed')], default=1)),
                ('transaction_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gateway', models.CharField(default='Zarin_Pal', max_length=50)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HardDeletePayment',
            fields=[
            ],
            options={
                'verbose_name': 'deleted Payment',
                'verbose_name_plural': 'deleted Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payments.payment',),
        ),
    ]
