# Generated by Django 5.2.6 on 2025-10-09 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='store_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='stores.storeitem', verbose_name='آیتم فروشگاه'),
        ),
    ]
