# Generated by Django 5.2.6 on 2025-10-09 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام فروشگاه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address', verbose_name='آدرس')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL, verbose_name='مالک فروشگاه')),
            ],
            options={
                'verbose_name': 'فروشگاه',
                'verbose_name_plural': 'فروشگاه\u200cها',
                'permissions': [('can_activate_store', 'Can activate/deactivate store'), ('can_manage_store_owner', 'Can change store owner'), ('can_edit_store_address', 'Can edit store address'), ('can_manage_store_info', 'Can manage store info')],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='حذف شده')),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='تاریخ حذف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('sku', models.CharField(blank=True, help_text='شناسه انبارداری مختص این فروشگاه', max_length=100, verbose_name='SKU')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='stores.store', verbose_name='فروشگاه')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='products.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'کالای فروشگاه',
                'verbose_name_plural': 'کالاهای فروشگاه',
                'permissions': [('can_activate_item', 'Can activate/deactivate store item'), ('can_edit_price', 'Can edit store item price'), ('can_edit_stock', 'Can edit stock quantity'), ('can_manage_sku', 'Can manage SKU for store item')],
            },
        ),
    ]
