# Generated by Django 5.2.6 on 2025-09-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='فعال'),
        ),
    ]
