# Generated by Django 5.2.6 on 2025-10-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='stock_quantity',
            new_name='stock',
        ),
    ]
