# Generated by Django 5.2.6 on 2025-10-15 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_initial'),
        ('stores', '0002_rename_stock_quantity_storeitem_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={},
        ),
        migrations.AlterModelOptions(
            name='storeitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='store',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='variant',
        ),
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeitem',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.store'),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
