# Generated by Django 5.2.6 on 2025-10-07 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('percent', models.PositiveIntegerField()),
                ('expire_at', models.DateTimeField()),
                ('usage_limit', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ کل (بدون تخفیف)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ تخفیف')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ نهایی پرداخت')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'منتظر پرداخت'), (2, 'پرداخت شده'), (3, 'ارسال شده'), (4, 'تحویل شده'), (5, 'لغو شده'), (6, 'مرجوع شده')], default=1, verbose_name='وضعیت کلی سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری مرسوله')),
                ('description', models.TextField(blank=True, null=True, verbose_name='یادداشت مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت (RefID)')),
                ('payment_authority', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد Authority زرین\u200cپال')),
                ('shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address', verbose_name='آدرس ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
                'permissions': [('can_cancel_order', 'می\u200cتواند سفارش را لغو کند'), ('can_mark_shipped', 'می\u200cتواند سفارش را ارسال\u200cشده کند')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='قیمت در زمان خرید')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'در انتظار تایید'), (2, 'در حال آماده\u200cسازی'), (3, 'ارسال شده'), (4, 'تحویل داده شده'), (5, 'لغو شده'), (6, 'مرجوع شده')], default=1, verbose_name='وضعیت آیتم')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
                ('store_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stores.storeitem', verbose_name='آیتم فروشگاه')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'در انتظار پرداخت'), (2, 'موفق'), (3, 'ناموفق')], db_index=True, default=1, verbose_name='وضعیت پرداخت')),
                ('payment_gateway', models.CharField(blank=True, max_length=50, verbose_name='درگاه پرداخت')),
                ('transaction_id', models.CharField(blank=True, db_index=True, help_text='شناسه منحصر به فردی که از درگاه پرداخت دریافت می\u200cشود.', max_length=255, verbose_name='شناسه تراکنش')),
                ('gateway_response', models.JSONField(blank=True, help_text='پاسخ کامل دریافت شده از درگاه برای دیباگ و پیگیری.', null=True, verbose_name='پاسخ درگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discount', 'user')},
            },
        ),
    ]
