# Generated by Django 5.2.6 on 2025-10-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='store_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='stores.storeitem', verbose_name='آیتم فروشگاه'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش'),
        ),
        migrations.AlterUniqueTogether(
            name='discountusage',
            unique_together={('discount', 'user')},
        ),
    ]
