# Generated by Django 5.2.6 on 2025-09-22 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={},
        ),
        migrations.RemoveField(
            model_name='discount',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(default='test', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expire_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='orders.discount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('discount', 'user')},
            },
        ),
    ]
