# Generated by Django 5.2.6 on 2025-09-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_discount_options_remove_discount_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_authority',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد Authority زرین\u200cپال'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد پیگیری پرداخت (RefID)'),
        ),
    ]
