# Generated by Django 5.2.6 on 2025-09-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_authority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'منتظر پرداخت'), (2, 'پرداخت شده'), (3, 'ارسال شده'), (4, 'تحویل شده'), (5, 'لغو شده'), (6, 'مرجوع شده')], default=1, verbose_name='وضعیت کلی سفارش'),
        ),
    ]
