# Generated by Django 5.2.6 on 2025-10-19 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HardDeleteStore',
            fields=[
            ],
            options={
                'verbose_name': 'deleted Store',
                'verbose_name_plural': 'deleted Stores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stores.store',),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='products.product'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stores.store'),
        ),
        migrations.CreateModel(
            name='HardDeleteStoreItem',
            fields=[
            ],
            options={
                'verbose_name': 'deleted Store item',
                'verbose_name_plural': 'deleted Store items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('stores.storeitem',),
        ),
    ]
